blank_issues_enabled: false
contact_links:
  - name: TPC Community Support
    url: https://discord.com/channels/830201397974663229/1047005249224847400
    about: For issues involving anything not related to a TPC Resource.