name: Feature Request
description: Request a new feature in one of our web resources!
title: "[Feature Request]: "
assignees:
  - 'vFlyingCowboy'
body:
  - type: dropdown
    id: resource
    attributes:
      label: Resource
      description: Which web resources would you like to see this feature on?
      options:
        - Flight Crew Portal
        - Discord Bot
        - API
        - Flight School
        - Unknown
      default: 0
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Whats the Feature?
      description: Give us as much detail about the feature as you can!
    validations:
      required: true