name: Infrastructure Change Request
description: Request an update to the infrastructure!
title: "[Infra Change]: "
assignees:
  - 'vFlyingCowboy'
labels: ["infra-change-request"]
body:
  - type: dropdown
    id: resource
    attributes:
      label: Resource
      description: Which resource does this apply to?
      options:
        - Flight Crew Portal
        - Discord Bot v2
        - Discord Bot v3
        - API
        - API V3
        - Flight School
        - Documentation Website
        - Infrastructure
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Whats the Change?
      description: Give us as much detail about the change you are requesting!
    validations:
      required: true